name: Deploy to EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.PROJECT_DIR }}
          git pull origin master
          
          # Frontend
          # cd frontend
          # rm -rf build
          # cp -r ../../frontend/build .
          
          # Backend
          # cd ..
          source venv/bin/activate
          pip install -r requirements.txt
          echo -e "Current Directory $PWD"
          
          # Restart services
          sudo systemctl restart fastapi
          sudo systemctl restart nginx
          
          echo "Deployment completed!"