name: Deploy to EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build React App
      run: |
        cd frontend
        npm install
        npm run dev

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ secrets.PROJECT_DIR }}
          git pull origin master
          
          # Frontend
          cd frontend
          # rm -rf build
          # cp -r ../../frontend/build .
          
          # Backend
          # cd ..
          source venv/bin/activate
          pip install -r requirements.txt
          
          # Restart services
          sudo systemctl restart fastapi
          sudo systemctl restart nginx
          
          echo "Deployment completed!"